#!/bin/bash
FILE=$1

if [ ! -f src/$FILE.c ]; then
    echo "Cannot compile $FILE, file src/$FILE.c was not found"
    exit 1
    return
fi

echo Compilling $FILE...
if [ "$FILE" = "terminus" ]; then
    gcc -Iincludes -Wall src/$FILE.c -o Terminus
    echo "Stored in ./Terminus (terminus shell)"
else
    gcc -Iincludes -Wall src/$FILE.c -o bin/commands/$FILE
    echo Stored in bin/commands/$FILE
fi
